import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs';
import "./globals.css";
import HeroSection from "./HeroSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const hasClerkKey = Boolean(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY);

  const body = (
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
    >
      <SignedOut>
        <div className="min-h-screen">
          <HeroSection />
        </div>
      </SignedOut>
      <SignedIn>
        <div className="fixed top-4 right-4 z-50">
        </div>
        {children}
      </SignedIn>
      {!hasClerkKey && (
        <>
          <div className="fixed top-4 right-4 z-50">
          </div>
          {children}
        </>
      )}
    </body>
  );

  return hasClerkKey ? (
    <ClerkProvider>
      <html lang="en">
        {body}
      </html>
    </ClerkProvider>
  ) : (
    <html lang="en">
      {body}
    </html>
  );
}
